import {
  ArrowLeft,
  ArrowRight,
  Badge,
  Bell,
  BookOpen,
  Calendar,
  CalendarCheck,
  CalendarX,
  Camera,
  ChefHat,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  CirclePlus,
  CircleUser,
  CreditCard,
  Eye,
  EyeOff,
  Folder,
  Grid3x3,
  Heart,
  HelpCircle,
  History,
  IdCard,
  Inbox,
  LayoutDashboard,
  Link,
  List,
  LoaderCircle,
  Lock,
  LogOut,
  Mail,
  MailCheck,
  MapPin,
  Menu,
  MessageSquareText,
  Minus,
  MoreVertical,
  Pencil,
  Plus,
  Printer,
  ReceiptText,
  Save,
  Search,
  SearchX,
  Send,
  Settings,
  Shield,
  ShoppingCart,
  Star,
  Store,
  Trash2,
  Unlink,
  User,
  UserPlus,
  UserRoundX,
  Users,
  Utensils,
  UtensilsCrossed,
  Wallet,
  X,
} from 'lucide-react'

/** Material Symbols ligature names → lucide-react components (SVG, no font flash). */
export const ICON_MAP = {
  account_circle: CircleUser,
  add: Plus,
  add_circle: CirclePlus,
  add_link: Link,
  analytics: LayoutDashboard,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  badge: Badge,
  calendar_month: Calendar,
  category: Folder,
  check_circle: CircleCheck,
  chef_hat: ChefHat,
  chevron_left: ChevronLeft,
  chevron_down: ChevronDown,
  expand_more: ChevronDown,
  chevron_right: ChevronRight,
  close: X,
  dashboard: LayoutDashboard,
  delete: Trash2,
  edit: Pencil,
  error: CircleAlert,
  event_available: CalendarCheck,
  event_busy: CalendarX,
  favorite: Heart,
  grid_view: Grid3x3,
  group: Users,
  help: HelpCircle,
  history: History,
  inbox: Inbox,
  link_off: Unlink,
  location_on: MapPin,
  logout: LogOut,
  mail: Mail,
  mark_email_read: MailCheck,
  menu: Menu,
  menu_book: BookOpen,
  more_vert: MoreVertical,
  notifications: Bell,
  payments: Wallet,
  person: User,
  person_add: UserPlus,
  person_off: UserRoundX,
  photo_camera: Camera,
  print: Printer,
  progress_activity: LoaderCircle,
  rate_review: MessageSquareText,
  receipt_long: ReceiptText,
  remove: Minus,
  restaurant: Utensils,
  restaurant_menu: UtensilsCrossed,
  save: Save,
  search: Search,
  search_off: SearchX,
  security: Shield,
  send: Send,
  settings: Settings,
  shopping_cart: ShoppingCart,
  star: Star,
  storefront: Store,
  store: Store,
  table_restaurant: UtensilsCrossed,
  view_list: List,
  visibility: Eye,
  visibility_off: EyeOff,
  warning: CircleAlert,
}
